# Generated by Django 6.0.3 on 2026-03-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0003_batch_farm_hand_alter_batch_farm'),
        ('TaskManagement', '0002_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Harvest_yield.batch'),
        ),
    ]
