# Generated by Django 6.0.3 on 2026-03-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0007_alter_batch_farm_alter_batch_farmhand'),
        ('TaskManagement', '0003_task_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_reports', to='Harvest_yield.batch'),
        ),
    ]
