# Generated by Django 6.0.3 on 2026-03-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_farmhand',
        ),
    ]
