# Generated by Django 6.0.3 on 2026-03-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0002_delete_new_farmhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='farm_hand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Harvest_yield.farmhand'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_batches', to='Harvest_yield.farm'),
        ),
    ]
