# Generated by Django 6.0.3 on 2026-03-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0003_batch_farm_hand_alter_batch_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_batches', to='Harvest_yield.farm'),
        ),
    ]
