# Generated by Django 6.0.3 on 2026-03-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0004_alter_batch_farm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='farm_hand',
            new_name='farmhand',
        ),
    ]
