# Generated by Django 6.0.3 on 2026-03-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0005_rename_farm_hand_batch_farmhand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='planted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
