# Generated by Django 6.0.3 on 2026-03-26 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0006_alter_batch_planted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_batches', to='Harvest_yield.farm'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='farmhand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Harvest_yield.farmhand'),
        ),
    ]
