# Generated by Django 6.0.3 on 2026-03-30 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0007_alter_batch_farm_alter_batch_farmhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='correspondent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'farmcorrespondent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='institution',
            field=models.ForeignKey(limit_choices_to={'role': 'farminstitution'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
