# Generated by Django 6.0.3 on 2026-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0008_farm_correspondent_farm_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhand',
            name='certification_number',
            field=models.CharField(help_text='EU Organic / USDA / JAS etc.', max_length=100),
        ),
    ]
