# Generated by Django 6.0.3 on 2026-03-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0009_alter_farmhand_certification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhand',
            name='certification_number',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmhand',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
