# Generated by Django 6.0.3 on 2026-03-30 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0010_alter_farmhand_certification_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution_correspondent',
        ),
        migrations.AddField(
            model_name='user',
            name='associated_institution',
            field=models.ForeignKey(blank=True, help_text='The Institution this user works for.', limit_choices_to={'role': 'farminstitution'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='crop_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='batch',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='batch',
            name='farmhand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Harvest_yield.farmhand'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='farm',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='institution',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'farminstitution'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmhand',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmhand_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatmentlog',
            name='product_used',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
