# Generated by Django 6.0.3 on 2026-03-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0011_alter_batch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmhand',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
