# Generated by Django 6.0.3 on 2026-04-08 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0014_alter_user_options_alter_farmhand_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='treatmentlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='treatmentlog',
            name='product_used',
        ),
        migrations.AlterField(
            model_name='batch',
            name='farmhand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Harvest_yield.farmhand'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmhand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farms', to='Harvest_yield.farmhand'),
        ),
        migrations.AlterField(
            model_name='treatmentlog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='associated_institution',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'farminstitution'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farminstitution', 'Farm Institution'), ('farmhand', 'FarmHand'), ('farmcorrespondent', 'Farm Correspondent'), ('user', 'Standard User')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='FarmCorrespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_assigned', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
