# Generated by Django 6.0.3 on 2026-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_yield', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='farmhand',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
